# Generated by Django 4.2.2 on 2023-07-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punk_rock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performers',
            name='data',
            field=models.IntegerField(),
        ),
    ]
